### ISSUE TITLE
ERR installing

### ISSUE THREAD

**Issue by cpuminingpool** [MarcoCiaramella/yespower-web#1]
npm WARN read-shrinkwrap This version of npm is compatible with lockfileVersion@1, but package-lock.json was generated for lockfileVersion@2. I'll try to do my best with it!
npm ERR! code ENOSELF
npm ERR! Refusing to install package with name "@marco_ciaramella/yespower-web" under a package
npm ERR! also called "@marco_ciaramella/yespower-web". Did you name your project the same
npm ERR! as the dependency you're installing?
npm ERR!
npm ERR! For more information, see:
npm ERR!     <https://docs.npmjs.com/cli/install#limitations-of-npms-install-algorithm>

**Comment by MarcoCiaramella** [comment]
thanks for reporting. Which version of npm are you using? run` npm --version`

**Comment by cpuminingpool** [comment]
6.14.12

**Comment by MarcoCiaramella** [comment]
have you already tried this [solution](https://stackoverflow.com/questions/52179949/npm-err-refusing-to-install-package-with-name-packagename-under-a-package-also) ?

**Comment by cpuminingpool** [comment]
i got that fix now but adding the code to html does not work like it says do i need to make a js file or something?

**Comment by MarcoCiaramella** [comment]
@cpuminingpool npm modules in front-end part requires a bunlder like [webpack](https://webpack.js.org/). Put your code in a .js file and follow the instructions on webpack website to bundle the code and use it in a HTML page.
