### ISSUE TITLE
Can you make it support for YespowerR16 algo?

### ISSUE THREAD

**Issue by tuananh19961** [MarcoCiaramella/yespower-web#2]

**Comment by tuananh19961** [comment]
@MarcoCiaramella Can you help me here?

**Comment by MarcoCiaramella** [comment]
hello @tuananh19961  this module will be marked as deprecated soon. I'm working on an unified version of miner with support for yespower, yespowerR16, yescrypt, yescryptR8, yescryptR16, yescryptR32 and minotaurx. It will be released next week
